### ISSUE TITLE
uncaught exceptions print no details in heka format

### ISSUE THREAD

**Issue by jrgm** [mozilla/mozlog#8]
Production example:
`{"Timestamp":1454695192969000000,"Logger":"fxa-basket-proxy","Type":"uncaughtException","Severity":0,"Pid":2066,"EnvVersion":"2.0","Fields":{}}`

Part of the issue is in https://github.com/mozilla/mozlog/blob/master/lib/format.js#L77-L84, where `payload` is an instance of Error, and `for..in` enumerates nothing. However, at that point, it seems the stack isn't on that object anymore.

**Comment by jrgm** [comment]
This should be a priority to fix as it affects current production basket proxy.

**Comment by vladikoff** [comment]
@seanmonstar @rfk could you push the new 2.0.3 to npm? https://github.com/mozilla/mozlog/releases

**Comment by rfk** [comment]
>  could you push the new 2.0.3 to npm?

Done, and I added you as a collaborator on npm.
